=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/p04-xml-shema/p05-xml-shema- prosirenje-restrikcija/z01-xml-lista-poruka-prosirenje/lista-poruka-struktura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://uvit.math.rs" xmlns="http://uvit.math.rs" elementFormDefault="qualified">
  <xsd:element name="listaPoruka" type="ListaPorukaType" />
  <xsd:complexType name="ListaPorukaType">
    <xsd:sequence>
      <xsd:element name="pismo" type="PorukaType" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="PorukaType">
    <xsd:all>
      <xsd:element name="prima" type="OsobaType" />
      <xsd:element name="salje" type="OsobaType" />
      <xsd:element name="naslov" type="xsd:string" />
      <xsd:element name="tekst" type="xsd:string" />
    </xsd:all>
    <xsd:attribute name="redniBroj" type="xsd:integer" />
  </xsd:complexType>
  <xsd:complexType name="OsobaType">
    <xsd:all>
      <xsd:element name="ime" type="xsd:string" />
      <xsd:element name="prezime" type="xsd:string" />
      <xsd:element name="adresa" type="SRBAdresaType" />
      <xsd:element name="datumRodjenja" type="xsd:date" />
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="AdresaType">
    <xsd:sequence>
      <xsd:element name="ulica" type="xsd:string" />
      <xsd:element name="broj" type="xsd:int" default="0" />
      <xsd:element name="grad" type="xsd:string" default="N/A" />
      <xsd:element name="drzava" type="xsd:string" default="N/A" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="SRBAdresaType">
    <xsd:complexContent>
      <xsd:extension base="AdresaType">
        <xsd:sequence>
          <xsd:element name="gradPostanskiBroj" type="xsd:int" default="0" />
          <xsd:element name="adresaPAK" type="xsd:int" default="0"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="USAAdresaType">
    <xsd:complexContent>
      <xsd:extension base="AdresaType">
        <xsd:sequence>
          <xsd:element name="state" type="xsd:string" />
          <xsd:element name="zipcode" type="xsd:string" />
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/p04-xml-shema/p04-xml-shema-atributi/z02-xml-lista-poruka/lista-poruka-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- OK - lista poruka moze da bude jednoclana
-->

<listaPoruka xmlns="http://uvit.math.rs" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://uvit.math.rs lista-poruka-struktura.xsd">
  <poruka redniBroj="1">
    <prima>
        <ime>Владимир</ime>
        <prezime>Филиповић</prezime>
        <adresa></adresa>
        <datumRodjenja>
        1968-06-17
      </datumRodjenja>
    </prima>
    <salje>
        <ime>Софија</ime>
        <prezime>Филиповић</prezime>
        <adresa></adresa>
        <datumRodjenja>2003-12-17</datumRodjenja>
    </salje>
    <naslov>Подсетник</naslov>
    <tekst>Купи карте за утакмицу.</tekst>
  </poruka>
  <poruka redniBroj="2">
    <salje>
      <ime>Владимир</ime>
      <prezime>Филиповић</prezime>
      <adresa></adresa>
      <datumRodjenja>
        1968-06-17
      </datumRodjenja>
    </salje>
    <prima>
      <ime>Софија</ime>
      <prezime>Филиповић</prezime>
      <adresa></adresa>
      <datumRodjenja>2003-12-17</datumRodjenja>
    </prima>
    <naslov>Коју?</naslov>
    <tekst>Коју утакмицу? Кошарка или одбојка?</tekst>
  </poruka>
</listaPoruka>

=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/p04-xml-shema/p05-xml-shema- prosirenje-restrikcija/z01-xml-lista-poruka-prosirenje/lista-poruka-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- OK - lista pismo moze da bude jednoclana
-->

<listaPoruka xmlns="http://uvit.math.rs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uvit.math.rs lista-poruka-struktura.xsd">
  <pismo redniBroj="1">
    <prima>
      <ime>Владимир</ime>
      <prezime>Филиповић</prezime>
      <adresa>
        <ulica>Студентски трг</ulica>
        <broj>12</broj>
        <grad>Београд</grad>
        <drzava>Србија</drzava>
        <gradPostanskiBroj>11000</gradPostanskiBroj>
        <adresaPAK>123456</adresaPAK>
      </adresa>
      <datumRodjenja>
        1968-06-17
      </datumRodjenja>
    </prima>
    <salje>
      <ime>Софија</ime>
      <prezime>Филиповић</prezime>
      <adresa>
        <ulica></ulica>
        <broj></broj>
        <grad></grad>
        <drzava></drzava>
        <gradPostanskiBroj></gradPostanskiBroj>
        <adresaPAK></adresaPAK>
      </adresa>
      <datumRodjenja>2003-12-17</datumRodjenja>
    </salje>
    <naslov>Подсетник</naslov>
    <tekst>Купи карте за утакмицу.</tekst>
  </pismo>
  <pismo redniBroj="2">
    <salje>
      <ime>Владимир</ime>
      <prezime>Филиповић</prezime>
      <adresa>
        <ulica>Студентски трг</ulica>
        <broj>12</broj>
        <grad>Београд</grad>
        <drzava>Србија</drzava>
        <gradPostanskiBroj>11000</gradPostanskiBroj>
        <adresaPAK>123456</adresaPAK>
      </adresa>
      <datumRodjenja> 1968-06-17 </datumRodjenja>
    </salje>
    <prima>
      <ime>Софија</ime>
      <prezime>Филиповић</prezime>
      <adresa>
        <ulica></ulica>
        <broj></broj>
        <grad></grad>
        <drzava></drzava>
        <gradPostanskiBroj></gradPostanskiBroj>
        <adresaPAK></adresaPAK>
      </adresa>
      <datumRodjenja>2003-12-17</datumRodjenja>
    </prima>
    <naslov>Коју?</naslov>
    <tekst>Коју утакмицу? Кошарка или одбојка?</tekst>
  </pismo>
</listaPoruka>
