<?xml version="1.0"?>
<!DOCTYPE poruka [
<!ELEMENT poruka (prima,salje,naslov,tekst)>
<!ELEMENT prima (#PCDATA)>
<!ELEMENT salje (#PCDATA)>
<!ELEMENT naslov (#PCDATA)>
<!ELEMENT tekst (#PCDATA)>
]>
<poruka>
  <prima>Sanja</prima>
  <salje>Vlado</salje>
  <naslov>Podsetnik</naslov>
  <tekst>Kupi karte za utakmicu</tekst>
</poruka>