=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/xml-dtd/z03-xml-spoljasnji-dtd-zbirka-pesama/zbirka-pesama.dtd
<!ELEMENT zbirka - - (pesma+)>
<!ELEMENT pesma - - (naslov?, strofa+)>
<!ATTLIST pesma autor CDATA #REQUIRED>
<!ELEMENT naslov - O (#PCDATA)>
<!ELEMENT strofa - O (stih+)>
<!ELEMENT stih O O (#PCDATA)>

=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/xml-dtd/z03-xml-spoljasnji-dtd-zbirka-pesama/djulici.xml
<?xml version="1.0"?>
<!DOCTYPE zbirka SYSTEM "zbirka-pesama.dtd">
<zbirka>
    <pesma autor="Čika Jova Zmaj">
        <naslov>Žaba čita novine </naslov>
        <strofa>
            <stih> Sedi žaba sama</stih>
            <stih> na listu lokvanja.</stih>
            <stih> od žarkoga sunca</stih>
            <stih> štitom se zaklanja.</stih>
        </strofa>  
        <strofa>
            <stih> Da novine čita</stih>
            <stih> to vam slika kaže,</stih>
            <stih> al' ne mož' da nađe</stih>
            <stih> što joj oči traže.</stih>
        </strofa>  
        <strofa>
            <stih> Znate već o čemu</stih>
            <stih> žabe brigu vode:</stih>
            <stih> hoće li se skoro</stih>
            <stih> odseliti rode.</stih>
        </strofa>  
    </pesma>
</zbirka>
