<?xml version="1.0"?>
<!DOCTYPE pismo [
<!ELEMENT pismo (prima,salje,naslov,tekst)>
<!ELEMENT prima (#PCDATA)>
<!ELEMENT salje (#PCDATA)>
<!ELEMENT naslov (#PCDATA)>
<!ELEMENT tekst (#PCDATA)>
]>
<pismo>
  <prima>Sanja</prima>
  <salje>Vlado</salje>
  <naslov>Podsetnik</naslov>
  <tekst>Kupi karte za utakmicu</tekst>
</pismo>