=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/p04-xml-schema/p02-xml-shema-sekvenca/z02-xml-zbirka-pesama-sekvenca/zbirka-pesama.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://uvit.math.rs" xmlns="http://uvit.math.rs" elementFormDefault="qualified">
    <xsd:element name="zbirka" type="ZbirkaType" />
    <xsd:complexType name="ZbirkaType">
        <xsd:sequence>
            <xsd:element name="pesma" type="PesmaType" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="PesmaType">
        <xsd:sequence>
            <xsd:element name="naslov" type="xsd:string" minOccurs="0"/>
            <xsd:element name="strofa" type="StrofaType" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="autor" type="xsd:string" use="optional" />
    </xsd:complexType>
    <xsd:complexType name="StrofaType">
        <xsd:sequence>
            <xsd:element name="stih" type="xsd:string" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/p04-xml-shema/p03-xml-shema-tip/z02-xml-zbirka-pesama-sekvenca/decije-pesme.xml
<?xml version="1.0" encoding="UTF-8"?>

<zbirka xmlns="http://uvit.math.rs" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://uvit.math.rs zbirka-pesama.xsd">

    <pesma>
        <naslov>Žaba čita novine</naslov>
        <strofa>
            <stih>Sedi žaba sama</stih>
            <stih>na listu lokvanja.</stih>
            <stih>od žarkoga sunca</stih>
            <stih>štitom se zaklanja.</stih>
        </strofa>
        <strofa>
            <stih>Da novine čita</stih>
            <stih>to vam slika kaže,</stih>
            <stih>al' ne mož' da nađe</stih>
            <stih>što joj oči traže.</stih>
        </strofa>
        <strofa>
            <stih>Znate već o čemu</stih>
            <stih>žabe brigu vode:</stih>
            <stih>hoće li se skoro</stih>
            <stih>odseliti rode.</stih>
        </strofa>
    </pesma>
    <pesma>
        <naslov>Био једном један лав</naslov>
        <strofa>
            <stih>Био једном један лав</stih>
            <stih>Какав лав? Страшан лав!</stih>
            <stih>Нарогушен и љут сав</stih>
            <stih>Страшно! Страшно!</stih>
        </strofa>
        <strofa>
            <stih>Не питајте шта је јео</stih>
            <stih>Тај је јео шта је хтео</stih>
            <stih>Трамвај цео и облака један део</stih>
            <stih>Страшно! Страшно!</stih>
        </strofa>
    </pesma>
</zbirka>

=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/p04-xml-schema/p02-xml-shema-sekvenca/z02-xml-zbirka-pesama-sekvenca/djulici.xml
<?xml version="1.0" encoding="UTF-8"?>

<zbirka xmlns="http://uvit.math.rs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uvit.math.rs zbirka-pesama.xsd">

    <pesma autor="Čika Jova Zmaj">
        <naslov>Žaba čita novine </naslov>
        <strofa>
            <stih> Sedi žaba sama</stih>
            <stih> na listu lokvanja.</stih>
            <stih> od žarkoga sunca</stih>
            <stih> štitom se zaklanja.</stih>
        </strofa>  
        <strofa>
            <stih> Da novine čita</stih>
            <stih> to vam slika kaže,</stih>
            <stih> al' ne mož' da nađe</stih>
            <stih> što joj oči traže.</stih>
        </strofa>  
        <strofa>
            <stih> Znate već o čemu</stih>
            <stih> žabe brigu vode:</stih>
            <stih> hoće li se skoro</stih>
            <stih> odseliti rode.</stih>
        </strofa>  
    </pesma>
</zbirka>
