=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/p04-xml-shema/p03-xml-shema-tip/z03-xml-lista-poruka/lista-poruka-struktura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://uvit.math.rs" xmlns="http://uvit.math.rs" elementFormDefault="qualified">
  <xsd:element name="listaPoruka" type="ListaPorukaType" />
  <xsd:complexType name="ListaPorukaType">
    <xsd:sequence>
      <xsd:element name="pismo" type="PorukaType" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="PorukaType">
    <xsd:all>
      <xsd:element name="prima" type="xsd:string" />
      <xsd:element name="salje" type="xsd:string" />
      <xsd:element name="naslov" type="xsd:string" />
      <xsd:element name="tekst" type="xsd:string" />
    </xsd:all>
  </xsd:complexType>

</xsd:schema>

=== MatfUVIT/primeri-predavanja-2020-21/sgml-dtd-xml/p04-xml-shema/p03-xml-shema-tip/z03-xml-lista-poruka/lista-poruka-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- OK - lista pismo moze da bude jednoclana
-->

<listaPoruka xmlns="http://uvit.math.rs" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://uvit.math.rs lista-poruka-struktura.xsd">
  <pismo>
    <prima>Sanja</prima>
    <salje>Vlado</salje>
    <naslov>Podsetnik</naslov>
    <tekst>Kupi karte za utakmicu</tekst>
  </pismo>
  <pismo>
    <salje>Sanja</salje>
    <prima>Vlado</prima>
    <naslov></naslov>
    <tekst>Kupila :)</tekst>
  </pismo>

</listaPoruka>
